services:
  web:
    build: .
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate && gunicorn mysite.wsgi --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
  postgres_data:
