# Generated by Django 5.0.4 on 2024-04-13 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_description_homepage_images'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='images',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('images', models.ManyToManyField(related_name='project_images', to='wagtailimages.image')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='home.project'),
        ),
    ]
