# Generated by Django 5.0.4 on 2024-04-13 19:13

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_description_remove_homepage_images_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='projects',
            field=modelcluster.fields.ParentalManyToManyField(related_name='projects', to='home.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=modelcluster.fields.ParentalManyToManyField(related_name='project_images', to='wagtailimages.image'),
        ),
    ]
