# Generated by Django 5.0.4 on 2024-04-13 19:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_projects_alter_project_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.homepage'),
        ),
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
