# Generated by Django 5.0.4 on 2024-04-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_project_options_remove_homepage_projects_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(related_name='project_images', to='wagtailimages.image'),
        ),
    ]
