# Generated by Django 5.0.4 on 2024-04-14 02:13

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_project_images'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=modelcluster.fields.ParentalManyToManyField(related_name='project_images', to='wagtailimages.image'),
        ),
    ]
