# Generated by Django 5.0.4 on 2024-04-14 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_project_images_projectimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('facebooks_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='Tiktok URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
