# Generated by Django 5.0.4 on 2024-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_navigationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
